# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMk2lmvor53ONaekHJX9tDLsIOUSQBta
"""

!pip install datasets pandas

# Importamos librerías
from datasets import load_dataset
import pandas as pd

# Repositorio de Hugging Face
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"

# Cargamos el dataset
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()  # Convertimos a tabla tipo Excel

# Revisamos cuántas filas y columnas hay
print("Dimensiones del dataset:", df.shape)
print(df.head())  # Muestra las primeras 5 filas

# Ejemplo de análisis: promedio de goles por partido
promedio_goles = df["total_goals"].mean()
print("Promedio de goles por partido:", round(promedio_goles, 2))

# 1️⃣ Importamos librerías
from datasets import load_dataset
import pandas as pd

# 2️⃣ Repositorio del dataset en Hugging Face
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"

# 3️⃣ Cargamos el dataset
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()

# 4️⃣ Mostramos tamaño y primeras filas
print("Dimensiones del dataset (filas, columnas):", df.shape)
print("Primeras 5 filas:")
print(df.head())

# 5️⃣ Lista de las 5 grandes ligas europeas
ligas_grandes = ["Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1"]

# 6️⃣ Filtrar todas las ligas en un solo DataFrame
df_ligas = df[df["competition_name"].isin(ligas_grandes)]

print("Número de partidos en las 5 ligas:", df_ligas.shape[0])
print("Primeras filas de las 5 ligas:")
print(df_ligas.head())

# 7️⃣ Guardar CSV con todas las 5 ligas
df_ligas.to_csv("Ligas_5_Grandes_2024_2025.csv", index=False)
print("CSV guardado: Ligas_5_Grandes_2024_2025.csv")

# 8️⃣ Estadísticas generales por liga
for liga in ligas_grandes:
    df_liga = df_ligas[df_ligas["competition_name"] == liga]
    total_partidos = df_liga.shape[0]
    promedio_goles = df_liga["total_goals"].mean()
    print(f"\nLiga: {liga}")
    print("Partidos:", total_partidos)
    print("Promedio de goles por partido:", round(promedio_goles,2))

    # Ejemplo Over/Under 2.5
    over_2_5 = (df_liga["total_goals"] > 2.5).sum()
    under_2_5 = (df_liga["total_goals"] <= 2.5).sum()
    print("Partidos Over 2.5:", over_2_5)
    print("Partidos Under 2.5:", under_2_5)

    # Ejemplo ambos equipos marcan (BTTS)
    btts = ((df_liga["fulltime_home"] > 0) & (df_liga["fulltime_away"] > 0)).sum()
    print("Partidos Ambos marcan (BTTS):", btts)

# 1️⃣ Importar librerías
from datasets import load_dataset
import pandas as pd
import numpy as np

# 2️⃣ Cargar dataset desde Hugging Face (si no lo habías cargado)
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()

# 3️⃣ Filtrar las 5 grandes ligas
ligas_grandes = ["Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1"]
df_ligas = df[df["competition_name"].isin(ligas_grandes)]

# 4️⃣ Función para resumen por equipo
def resumen_equipo(df, equipo):
    local = df[df["home_team"] == equipo]
    visitante = df[df["away_team"] == equipo]

    partidos = local.shape[0] + visitante.shape[0]
    goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
    goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
    promedio_goles = goles_anotados / partidos if partidos > 0 else 0

    over_2_5 = ((local["total_goals"] > 2.5).sum() + (visitante["total_goals"] > 2.5).sum())
    under_2_5 = ((local["total_goals"] <= 2.5).sum() + (visitante["total_goals"] <= 2.5).sum())
    btts = ((local["fulltime_home"] > 0) & (local["fulltime_away"] > 0)).sum() + \
           ((visitante["fulltime_home"] > 0) & (visitante["fulltime_away"] > 0)).sum()

    print(f"=== Resumen: {equipo} ===")
    print(f"Partidos jugados: {partidos}")
    print(f"Goles anotados: {goles_anotados}")
    print(f"Goles recibidos: {goles_recibidos}")
    print(f"Promedio de goles por partido: {round(promedio_goles,2)}")
    print(f"Partidos Over 2.5: {over_2_5}")
    print(f"Partidos Under 2.5: {under_2_5}")
    print(f"Partidos Ambos marcan (BTTS): {btts}")

# 5️⃣ Función resumen por liga
def resumen_liga(df, liga):
    df_liga = df[df["competition_name"] == liga]
    total_partidos = df_liga.shape[0]
    promedio_goles = df_liga["total_goals"].mean()
    over_2_5 = (df_liga["total_goals"] > 2.5).sum()
    under_2_5 = (df_liga["total_goals"] <= 2.5).sum()
    btts = ((df_liga["fulltime_home"]>0) & (df_liga["fulltime_away"]>0)).sum()

    print(f"=== Resumen liga: {liga} ===")
    print(f"Partidos: {total_partidos}")
    print(f"Promedio de goles: {round(promedio_goles,2)}")
    print(f"Over 2.5: {over_2_5}")
    print(f"Under 2.5: {under_2_5}")
    print(f"BTTS: {btts}")

# 6️⃣ Ejemplo: resumen Premier League
resumen_liga(df_ligas, "Premier League")

# 7️⃣ Ejemplo: resumen por equipo
resumen_equipo(df_ligas, "Arsenal")

# 1️⃣ Librerías necesarias
from datasets import load_dataset
import pandas as pd
import numpy as np
from scipy.stats import poisson

# 2️⃣ Cargar dataset
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()

# 3️⃣ Filtrar las 5 grandes ligas
ligas_grandes = ["Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1"]
df_ligas = df[df["competition_name"].isin(ligas_grandes)]

# 4️⃣ Función para calcular promedios de goles por equipo
def calcular_promedios(df):
    equipos = pd.concat([df["home_team"], df["away_team"]]).unique()
    data = {}
    for equipo in equipos:
        local = df[df["home_team"] == equipo]
        visitante = df[df["away_team"] == equipo]

        goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
        goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
        partidos = local.shape[0] + visitante.shape[0]

        media_anotados = goles_anotados / partidos if partidos > 0 else 0
        media_recibidos = goles_recibidos / partidos if partidos > 0 else 0

        data[equipo] = {"gf": media_anotados, "gc": media_recibidos}
    return data

promedios = calcular_promedios(df_ligas)

# 5️⃣ Función para predecir resultado con Poisson
def predecir_poisson(local, visitante, promedios):
    lambda_local = promedios[local]["gf"]
    lambda_visitante = promedios[visitante]["gf"]

    # Probabilidades básicas 0-5 goles
    max_goles = 5
    prob_local = [poisson.pmf(i, lambda_local) for i in range(max_goles+1)]
    prob_visitante = [poisson.pmf(i, lambda_visitante) for i in range(max_goles+1)]

    # Probabilidades de 1X2
    prob_1 = sum([prob_local[i]*sum(prob_visitante[j] for j in range(i)) for i in range(max_goles+1)])
    prob_X = sum([prob_local[i]*prob_visitante[i] for i in range(max_goles+1)])
    prob_2 = sum([sum(prob_local[i] for i in range(j)) * prob_visitante[j] for j in range(max_goles+1)])

    # Probabilidad de Over/Under 2.5
    over_2_5 = 1 - sum([prob_local[i]*prob_visitante[j] for i in range(max_goles+1) for j in range(max_goles+1) if i+j <=2])
    under_2_5 = 1 - over_2_5

    # Ambos marcan (BTTS)
    btts = 1 - (prob_local[0]*sum(prob_visitante) + prob_visitante[0]*sum(prob_local))

    return {
        "1": round(prob_1*100,1),
        "X": round(prob_X*100,1),
        "2": round(prob_2*100,1),
        "Over2.5": round(over_2_5*100,1),
        "Under2.5": round(under_2_5*100,1),
        "BTTS": round(btts*100,1)
    }

# 6️⃣ Aplicar predicción a todos los partidos
resultados = []
for idx, fila in df_ligas.iterrows():
    local = fila["home_team"]
    visitante = fila["away_team"]
    pred = predecir_poisson(local, visitante, promedios)

    resultados.append({
        "Liga": fila["competition_name"],
        "Fecha": fila["date_utc"],
        "Local": local,
        "Visitante": visitante,
        "1": pred["1"],
        "X": pred["X"],
        "2": pred["2"],
        "Over2.5": pred["Over2.5"],
        "Under2.5": pred["Under2.5"],
        "BTTS": pred["BTTS"]
    })

df_predicciones = pd.DataFrame(resultados)

# 7️⃣ Guardar CSV con predicciones
df_predicciones.to_csv("Predicciones_5_ligas_2024_2025.csv", index=False)
print("CSV de predicciones guardado: Predicciones_5_ligas_2024_2025.csv")

# 8️⃣ Mostrar primeras filas
df_predicciones.head()

# 1️⃣ Importar librerías necesarias
from datasets import load_dataset
import pandas as pd
import numpy as np

# 2️⃣ Cargar dataset desde Hugging Face
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()  # Convertir a DataFrame tipo Excel

# 3️⃣ Seleccionar las 5 grandes ligas
ligas_grandes = ["Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1"]
df_ligas = df[df["competition_name"].isin(ligas_grandes)]

# 4️⃣ Función para generar resumen por equipo
def resumen_equipo(df, equipo):
    local = df[df["home_team"] == equipo]
    visitante = df[df["away_team"] == equipo]

    partidos = local.shape[0] + visitante.shape[0]
    goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
    goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
    promedio_goles = goles_anotados / partidos if partidos > 0 else 0

    over_0_5 = ((local["total_goals"] > 0.5).sum() + (visitante["total_goals"] > 0.5).sum())
    under_0_5 = ((local["total_goals"] <= 0.5).sum() + (visitante["total_goals"] <= 0.5).sum())
    over_1_5 = ((local["total_goals"] > 1.5).sum() + (visitante["total_goals"] > 1.5).sum())
    under_1_5 = ((local["total_goals"] <= 1.5).sum() + (visitante["total_goals"] <= 1.5).sum())
    over_2_5 = ((local["total_goals"] > 2.5).sum() + (visitante["total_goals"] > 2.5).sum())
    under_2_5 = ((local["total_goals"] <= 2.5).sum() + (visitante["total_goals"] <= 2.5).sum())
    btts = ((local["fulltime_home"] > 0) & (local["fulltime_away"] > 0)).sum() + \
           ((visitante["fulltime_home"] > 0) & (visitante["fulltime_away"] > 0)).sum()

    resumen = {
        "Equipo": equipo,
        "Partidos jugados": partidos,
        "Goles anotados": goles_anotados,
        "Goles recibidos": goles_recibidos,
        "Promedio goles": round(promedio_goles, 2),
        "Over 0.5": over_0_5,
        "Under 0.5": under_0_5,
        "Over 1.5": over_1_5,
        "Under 1.5": under_1_5,
        "Over 2.5": over_2_5,
        "Under 2.5": under_2_5,
        "BTTS": btts
    }
    return resumen

# 5️⃣ Función para generar resumen por liga
def resumen_liga(df, liga):
    df_liga = df[df["competition_name"] == liga]
    equipos = pd.unique(df_liga["home_team"].tolist() + df_liga["away_team"].tolist())

    resumen_equipos = [resumen_equipo(df_liga, equipo) for equipo in equipos]
    df_resumen = pd.DataFrame(resumen_equipos)

    # Guardar CSV de la liga
    nombre_csv = f"Resumen_{liga.replace(' ', '_')}_2024_2025.csv"
    df_resumen.to_csv(nombre_csv, index=False)
    print(f"CSV guardado: {nombre_csv}")

    # Estadísticas globales de la liga
    total_partidos = df_liga.shape[0]
    promedio_goles = df_liga["total_goals"].mean()
    over_2_5 = (df_liga["total_goals"] > 2.5).sum()
    under_2_5 = (df_liga["total_goals"] <= 2.5).sum()
    btts = ((df_liga["fulltime_home"] > 0) & (df_liga["fulltime_away"] > 0)).sum()

    print(f"=== Resumen liga: {liga} ===")
    print(f"Partidos: {total_partidos}")
    print(f"Promedio goles por partido: {round(promedio_goles,2)}")
    print(f"Over 2.5: {over_2_5}")
    print(f"Under 2.5: {under_2_5}")
    print(f"BTTS: {btts}")

# 6️⃣ Ejecutar resumen para cada liga automáticamente
for liga in ligas_grandes:
    resumen_liga(df_ligas, liga)

# ✅ Al final tendrás 5 CSVs separados, uno por cada liga, listos para tu futura aplicación

# 1️⃣ Importar librerías
from datasets import load_dataset
import pandas as pd
import numpy as np

# 2️⃣ Cargar dataset desde Hugging Face
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()  # Convertir a DataFrame tipo Excel

# 3️⃣ Definir todas las ligas que queremos analizar
ligas = [
    "Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1",  # 5 grandes
    "Eredivisie", "Eerste Divisie",  # Holanda
    "Süper Lig", "TFF 1. Lig",       # Turquía
    "A-League", "Úrvalsdeild"        # Australia e Islandia
]

# Filtrar solo las ligas deseadas
df_ligas = df[df["competition_name"].isin(ligas)]

# 4️⃣ Función para resumen por equipo
def resumen_equipo(df, equipo):
    local = df[df["home_team"] == equipo]
    visitante = df[df["away_team"] == equipo]

    partidos = local.shape[0] + visitante.shape[0]
    goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
    goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
    promedio_goles = goles_anotados / partidos if partidos > 0 else 0

    over_0_5 = ((local["total_goals"] > 0.5).sum() + (visitante["total_goals"] > 0.5).sum())
    under_0_5 = ((local["total_goals"] <= 0.5).sum() + (visitante["total_goals"] <= 0.5).sum())
    over_1_5 = ((local["total_goals"] > 1.5).sum() + (visitante["total_goals"] > 1.5).sum())
    under_1_5 = ((local["total_goals"] <= 1.5).sum() + (visitante["total_goals"] <= 1.5).sum())
    over_2_5 = ((local["total_goals"] > 2.5).sum() + (visitante["total_goals"] > 2.5).sum())
    under_2_5 = ((local["total_goals"] <= 2.5).sum() + (visitante["total_goals"] <= 2.5).sum())
    btts = ((local["fulltime_home"] > 0) & (local["fulltime_away"] > 0)).sum() + \
           ((visitante["fulltime_home"] > 0) & (visitante["fulltime_away"] > 0)).sum()

    resumen = {
        "Equipo": equipo,
        "Partidos jugados": partidos,
        "Goles anotados": goles_anotados,
        "Goles recibidos": goles_recibidos,
        "Promedio goles": round(promedio_goles, 2),
        "Over 0.5": over_0_5,
        "Under 0.5": under_0_5,
        "Over 1.5": over_1_5,
        "Under 1.5": under_1_5,
        "Over 2.5": over_2_5,
        "Under 2.5": under_2_5,
        "BTTS": btts
    }
    return resumen

# 5️⃣ Función para resumen por liga y guardar CSV
def resumen_liga(df, liga):
    df_liga = df[df["competition_name"] == liga]
    equipos = pd.unique(df_liga["home_team"].tolist() + df_liga["away_team"].tolist())

    resumen_equipos = [resumen_equipo(df_liga, equipo) for equipo in equipos]
    df_resumen = pd.DataFrame(resumen_equipos)

    # Guardar CSV
    nombre_csv = f"Resumen_{liga.replace(' ', '_')}_2024_2025.csv"
    df_resumen.to_csv(nombre_csv, index=False)
    print(f"CSV guardado: {nombre_csv}")

    # Estadísticas globales de la liga
    total_partidos = df_liga.shape[0]
    promedio_goles = df_liga["total_goals"].mean()
    over_2_5 = (df_liga["total_goals"] > 2.5).sum()
    under_2_5 = (df_liga["total_goals"] <= 2.5).sum()
    btts = ((df_liga["fulltime_home"] > 0) & (df_liga["fulltime_away"] > 0)).sum()

    print(f"=== Resumen liga: {liga} ===")
    print(f"Partidos: {total_partidos}")
    print(f"Promedio goles por partido: {round(promedio_goles,2)}")
    print(f"Over 2.5: {over_2_5}")
    print(f"Under 2.5: {under_2_5}")
    print(f"BTTS: {btts}")

# 6️⃣ Ejecutar resumen para todas las ligas
for liga in ligas:
    resumen_liga(df_ligas, liga)

# ✅ Resultado: CSV separados para cada liga, listos para tu aplicación

# 1️⃣ Librerías
import pandas as pd
import numpy as np

# 2️⃣ Cargar todos los CSV de ligas que guardaste
# Por ejemplo, Premier League:
df_pl = pd.read_csv("Resumen_Premier_League_2024_2025.csv")
# Haz lo mismo para las demás ligas si quieres trabajar cada una por separado

# 3️⃣ Función de predicción simple basada en promedio de goles
def predecir_partido(local, visitante, df_liga):
    """
    Predice ganador, Over/Under 0.5,1.5,2.5 y BTTS
    usando promedios históricos de la liga.
    """
    equipo_local = df_liga[df_liga["Equipo"] == local]
    equipo_visita = df_liga[df_liga["Equipo"] == visitante]

    # Si alguno no tiene datos, devolver vacíos
    if equipo_local.empty or equipo_visita.empty:
        return pd.Series({
            "Local": local,
            "Visitante": visitante,
            "Predicción Ganador": "ND",
            "Over 0.5": "ND",
            "Over 1.5": "ND",
            "Over 2.5": "ND",
            "BTTS": "ND"
        })

    # Promedio goles anotados y recibidos
    goles_local = equipo_local["Promedio goles"].values[0]
    goles_visita = equipo_visita["Promedio goles"].values[0]

    # Ganador simple
    if goles_local > goles_visita:
        ganador = "Local"
    elif goles_visita > goles_local:
        ganador = "Visitante"
    else:
        ganador = "Empate"

    # Over/Under 0.5,1.5,2.5
    over_05 = "Sí" if goles_local + goles_visita > 0.5 else "No"
    over_15 = "Sí" if goles_local + goles_visita > 1.5 else "No"
    over_25 = "Sí" if goles_local + goles_visita > 2.5 else "No"

    # Ambos marcan (BTTS)
    btts = "Sí" if (equipo_local["Goles anotados"].values[0] > 0 and equipo_visita["Goles anotados"].values[0] > 0) else "No"

    return pd.Series({
        "Local": local,
        "Visitante": visitante,
        "Predicción Ganador": ganador,
        "Over 0.5": over_05,
        "Over 1.5": over_15,
        "Over 2.5": over_25,
        "BTTS": btts
    })

# 4️⃣ Lista de partidos a predecir (ejemplo)
partidos_proximos = [
    {"Local": "Arsenal", "Visitante": "Manchester City"},
    {"Local": "Barcelona", "Visitante": "Real Madrid"},
    {"Local": "Bayern Munich", "Visitante": "Borussia Dortmund"}
]

df_partidos = pd.DataFrame(partidos_proximos)

# 5️⃣ Aplicar predicciones
df_predicciones = df_partidos.apply(lambda row: predecir_partido(row["Local"], row["Visitante"], df_pl), axis=1)

# 6️⃣ Guardar CSV de predicciones
df_predicciones.to_csv("Predicciones_Premier_League.csv", index=False)
print("CSV de predicciones guardado: Predicciones_Premier_League.csv")

# 7️⃣ Mostrar primeras filas
df_predicciones.head()

# 🚀 Todo en una sola celda: resumen + predicciones + CSVs

# 1️⃣ Librerías necesarias
!pip install -q datasets pandas numpy scipy

from datasets import load_dataset
import pandas as pd
import numpy as np
from scipy.stats import poisson

# 2️⃣ Cargar dataset
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()

# 3️⃣ Filtrar las 5 grandes ligas
ligas_grandes = ["Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1"]
df_ligas = df[df["competition_name"].isin(ligas_grandes)]

# 4️⃣ Calcular promedios de goles por equipo
def calcular_promedios(df):
    equipos = pd.concat([df["home_team"], df["away_team"]]).unique()
    data = {}
    for equipo in equipos:
        local = df[df["home_team"] == equipo]
        visitante = df[df["away_team"] == equipo]

        goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
        goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
        partidos = local.shape[0] + visitante.shape[0]

        media_anotados = goles_anotados / partidos if partidos > 0 else 0
        media_recibidos = goles_recibidos / partidos if partidos > 0 else 0

        data[equipo] = {"gf": media_anotados, "gc": media_recibidos}
    return data

promedios = calcular_promedios(df_ligas)

# 5️⃣ Función de predicción Poisson
def predecir_poisson(local, visitante, promedios):
    lambda_local = promedios[local]["gf"]
    lambda_visitante = promedios[visitante]["gf"]

    max_goles = 5
    prob_local = [poisson.pmf(i, lambda_local) for i in range(max_goles+1)]
    prob_visitante = [poisson.pmf(i, lambda_visitante) for i in range(max_goles+1)]

    prob_1 = sum([prob_local[i]*sum(prob_visitante[j] for j in range(i)) for i in range(max_goles+1)])
    prob_X = sum([prob_local[i]*prob_visitante[i] for i in range(max_goles+1)])
    prob_2 = sum([sum(prob_local[i] for i in range(j)) * prob_visitante[j] for j in range(max_goles+1)])

    over_2_5 = 1 - sum([prob_local[i]*prob_visitante[j] for i in range(max_goles+1) for j in range(max_goles+1) if i+j <=2])
    under_2_5 = 1 - over_2_5
    btts = 1 - (prob_local[0]*sum(prob_visitante) + prob_visitante[0]*sum(prob_local))

    return {
        "1": round(prob_1*100,1),
        "X": round(prob_X*100,1),
        "2": round(prob_2*100,1),
        "Over2.5": round(over_2_5*100,1),
        "Under2.5": round(under_2_5*100,1),
        "BTTS": round(btts*100,1)
    }

# 6️⃣ Generar predicciones para todos los partidos
resultados = []
for idx, fila in df_ligas.iterrows():
    local = fila["home_team"]
    visitante = fila["away_team"]
    pred = predecir_poisson(local, visitante, promedios)

    resultados.append({
        "Liga": fila["competition_name"],
        "Fecha": fila["date_utc"],
        "Local": local,
        "Visitante": visitante,
        "1": pred["1"],
        "X": pred["X"],
        "2": pred["2"],
        "Over2.5": pred["Over2.5"],
        "Under2.5": pred["Under2.5"],
        "BTTS": pred["BTTS"]
    })

df_predicciones = pd.DataFrame(resultados)

# 7️⃣ Guardar CSV general
df_predicciones.to_csv("Predicciones_5_ligas_2024_2025.csv", index=False)
print("✅ CSV general guardado: Predicciones_5_ligas_2024_2025.csv")

# 8️⃣ Guardar CSVs separados por liga
for liga in ligas_grandes:
    df_liga = df_predicciones[df_predicciones["Liga"] == liga]
    nombre_csv = f"Predicciones_{liga.replace(' ','_')}_2024_2025.csv"
    df_liga.to_csv(nombre_csv, index=False)
    print(f"CSV guardado: {nombre_csv}")

# 9️⃣ Mostrar primeras filas
df_predicciones.head()

# 1️⃣ Librerías necesarias
from datasets import load_dataset
import pandas as pd
import numpy as np
from scipy.stats import poisson

# 2️⃣ Cargar dataset
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()

# 3️⃣ Filtrar solo las 5 grandes ligas
ligas_grandes = ["Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1"]
df_ligas = df[df["competition_name"].isin(ligas_grandes)].copy()

# 4️⃣ Función resumen por equipo
def resumen_equipo(df, equipo):
    local = df[df["home_team"] == equipo]
    visitante = df[df["away_team"] == equipo]

    partidos = local.shape[0] + visitante.shape[0]
    goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
    goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
    promedio_goles = goles_anotados / partidos if partidos else 0

    over_0_5 = ((local["total_goals"] > 0.5).sum() + (visitante["total_goals"] > 0.5).sum())
    under_0_5 = ((local["total_goals"] <= 0.5).sum() + (visitante["total_goals"] <= 0.5).sum())
    over_1_5 = ((local["total_goals"] > 1.5).sum() + (visitante["total_goals"] > 1.5).sum())
    under_1_5 = ((local["total_goals"] <= 1.5).sum() + (visitante["total_goals"] <= 1.5).sum())
    over_2_5 = ((local["total_goals"] > 2.5).sum() + (visitante["total_goals"] > 2.5).sum())
    under_2_5 = ((local["total_goals"] <= 2.5).sum() + (visitante["total_goals"] <= 2.5).sum())
    btts = ((local["fulltime_home"] > 0) & (local["fulltime_away"] > 0)).sum() + \
           ((visitante["fulltime_home"] > 0) & (visitante["fulltime_away"] > 0)).sum()

    return {
        "Equipo": equipo,
        "Partidos jugados": partidos,
        "Goles anotados": goles_anotados,
        "Goles recibidos": goles_recibidos,
        "Promedio goles": round(promedio_goles, 2),
        "Over 0.5": over_0_5,
        "Under 0.5": under_0_5,
        "Over 1.5": over_1_5,
        "Under 1.5": under_1_5,
        "Over 2.5": over_2_5,
        "Under 2.5": under_2_5,
        "BTTS": btts
    }

# 5️⃣ Función resumen por liga
def resumen_liga(df, liga):
    df_liga = df[df["competition_name"] == liga].copy()
    equipos = pd.unique(np.array(df_liga["home_team"].tolist() + df_liga["away_team"].tolist()))
    resumen_equipos = [resumen_equipo(df_liga, eq) for eq in equipos]
    df_resumen = pd.DataFrame(resumen_equipos)

    # Guardar CSV
    nombre_csv = f"Resumen_{liga.replace(' ','_')}_2024_2025.csv"
    df_resumen.to_csv(nombre_csv, index=False)
    print(f"CSV guardado: {nombre_csv}")

    # Estadísticas globales de la liga
    total_partidos = df_liga.shape[0]
    promedio_goles = df_liga["total_goals"].mean()
    over_2_5 = (df_liga["total_goals"] > 2.5).sum()
    under_2_5 = (df_liga["total_goals"] <= 2.5).sum()
    btts = ((df_liga["fulltime_home"] > 0) & (df_liga["fulltime_away"] > 0)).sum()

    print(f"=== Resumen liga: {liga} ===")
    print(f"Partidos: {total_partidos}")
    print(f"Promedio goles por partido: {round(promedio_goles,2)}")
    print(f"Over 2.5: {over_2_5}")
    print(f"Under 2.5: {under_2_5}")
    print(f"BTTS: {btts}")

# 6️⃣ Ejecutar resumen para las 5 ligas automáticamente
for liga in ligas_grandes:
    resumen_liga(df_ligas, liga)

# 7️⃣ Función Poisson para predicción de partidos
def calcular_promedios(df):
    equipos = pd.concat([df["home_team"], df["away_team"]]).unique()
    data = {}
    for equipo in equipos:
        local = df[df["home_team"] == equipo]
        visitante = df[df["away_team"] == equipo]
        partidos = local.shape[0] + visitante.shape[0]
        goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
        goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
        data[equipo] = {
            "gf": goles_anotados / partidos if partidos else 0,
            "gc": goles_recibidos / partidos if partidos else 0
        }
    return data

promedios = calcular_promedios(df_ligas)

def predecir_poisson(local, visitante, promedios):
    lambda_local = promedios[local]["gf"]
    lambda_visitante = promedios[visitante]["gf"]
    max_goles = 5
    prob_local = [poisson.pmf(i, lambda_local) for i in range(max_goles+1)]
    prob_visitante = [poisson.pmf(i, lambda_visitante) for i in range(max_goles+1)]
    prob_1 = sum([prob_local[i]*sum(prob_visitante[j] for j in range(i)) for i in range(max_goles+1)])
    prob_X = sum([prob_local[i]*prob_visitante[i] for i in range(max_goles+1)])
    prob_2 = sum([sum(prob_local[i] for i in range(j)) * prob_visitante[j] for j in range(max_goles+1)])
    over_2_5 = 1 - sum([prob_local[i]*prob_visitante[j] for i in range(max_goles+1) for j in range(max_goles+1) if i+j <=2])
    under_2_5 = 1 - over_2_5
    btts = 1 - (prob_local[0]*sum(prob_visitante) + prob_visitante[0]*sum(prob_local))
    return {"1": round(prob_1*100,1), "X": round(prob_X*100,1), "2": round(prob_2*100,1),
            "Over2.5": round(over_2_5*100,1), "Under2.5": round(under_2_5*100,1), "BTTS": round(btts*100,1)}

# 8️⃣ Generar predicciones para todos los partidos
resultados = []
for idx, fila in df_ligas.iterrows():
    local = fila["home_team"]
    visitante = fila["away_team"]
    pred = predecir_poisson(local, visitante, promedios)
    resultados.append({
        "Liga": fila["competition_name"],
        "Fecha": fila["date_utc"],
        "Local": local,
        "Visitante": visitante,
        "1": pred["1"],
        "X": pred["X"],
        "2": pred["2"],
        "Over2.5": pred["Over2.5"],
        "Under2.5": pred["Under2.5"],
        "BTTS": pred["BTTS"]
    })

df_predicciones = pd.DataFrame(resultados)
df_predicciones.to_csv("Predicciones_5_ligas_2024_2025.csv", index=False)
print("CSV de predicciones guardado: Predicciones_5_ligas_2024_2025.csv")

# 9️⃣ Mostrar primeras filas
df_predicciones.head()

# app_professional.py

# 1️⃣ Librerías necesarias
from datasets import load_dataset
import pandas as pd
import numpy as np
from scipy.stats import poisson

# 2️⃣ Cargar dataset desde Hugging Face
repositorio = "TarekMasryo/Football-Matches-2024-2025-season"
dataset = load_dataset(repositorio)
df = dataset["train"].to_pandas()  # Convertimos a DataFrame tipo Excel

# 3️⃣ Seleccionar las 5 grandes ligas
ligas_grandes = ["Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1"]
df_ligas = df[df["competition_name"].isin(ligas_grandes)]

# 4️⃣ Función para generar resumen por equipo
def resumen_equipo(df, equipo):
    local = df[df["home_team"] == equipo]
    visitante = df[df["away_team"] == equipo]

    partidos = local.shape[0] + visitante.shape[0]
    goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
    goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
    promedio_goles = goles_anotados / partidos if partidos > 0 else 0

    over_0_5 = ((local["total_goals"] > 0.5).sum() + (visitante["total_goals"] > 0.5).sum())
    under_0_5 = ((local["total_goals"] <= 0.5).sum() + (visitante["total_goals"] <= 0.5).sum())
    over_1_5 = ((local["total_goals"] > 1.5).sum() + (visitante["total_goals"] > 1.5).sum())
    under_1_5 = ((local["total_goals"] <= 1.5).sum() + (visitante["total_goals"] <= 1.5).sum())
    over_2_5 = ((local["total_goals"] > 2.5).sum() + (visitante["total_goals"] > 2.5).sum())
    under_2_5 = ((local["total_goals"] <= 2.5).sum() + (visitante["total_goals"] <= 2.5).sum())
    btts = ((local["fulltime_home"] > 0) & (local["fulltime_away"] > 0)).sum() + \
           ((visitante["fulltime_home"] > 0) & (visitante["fulltime_away"] > 0)).sum()

    resumen = {
        "Equipo": equipo,
        "Partidos jugados": partidos,
        "Goles anotados": goles_anotados,
        "Goles recibidos": goles_recibidos,
        "Promedio goles": round(promedio_goles, 2),
        "Over 0.5": over_0_5,
        "Under 0.5": under_0_5,
        "Over 1.5": over_1_5,
        "Under 1.5": under_1_5,
        "Over 2.5": over_2_5,
        "Under 2.5": under_2_5,
        "BTTS": btts
    }
    return resumen

# 5️⃣ Función para resumen por liga
def resumen_liga(df, liga):
    df_liga = df[df["competition_name"] == liga]
    equipos = pd.unique(df_liga["home_team"].tolist() + df_liga["away_team"].tolist())
    resumen_equipos = [resumen_equipo(df_liga, equipo) for equipo in equipos]
    df_resumen = pd.DataFrame(resumen_equipos)

    # Guardar CSV de la liga
    nombre_csv = f"Resumen_{liga.replace(' ', '_')}_2024_2025.csv"
    df_resumen.to_csv(nombre_csv, index=False)
    print(f"CSV guardado: {nombre_csv}")

    # Estadísticas globales de la liga
    total_partidos = df_liga.shape[0]
    promedio_goles = df_liga["total_goals"].mean()
    over_2_5 = (df_liga["total_goals"] > 2.5).sum()
    under_2_5 = (df_liga["total_goals"] <= 2.5).sum()
    btts = ((df_liga["fulltime_home"] > 0) & (df_liga["fulltime_away"] > 0)).sum()

    print(f"=== Resumen liga: {liga} ===")
    print(f"Partidos: {total_partidos}")
    print(f"Promedio goles por partido: {round(promedio_goles,2)}")
    print(f"Over 2.5: {over_2_5}")
    print(f"Under 2.5: {under_2_5}")
    print(f"BTTS: {btts}")

# 6️⃣ Calcular promedios de goles por equipo para Poisson
def calcular_promedios(df):
    equipos = pd.concat([df["home_team"], df["away_team"]]).unique()
    data = {}
    for equipo in equipos:
        local = df[df["home_team"] == equipo]
        visitante = df[df["away_team"] == equipo]
        goles_anotados = local["fulltime_home"].sum() + visitante["fulltime_away"].sum()
        goles_recibidos = local["fulltime_away"].sum() + visitante["fulltime_home"].sum()
        partidos = local.shape[0] + visitante.shape[0]
        data[equipo] = {
            "gf": goles_anotados / partidos if partidos > 0 else 0,
            "gc": goles_recibidos / partidos if partidos > 0 else 0
        }
    return data

promedios = calcular_promedios(df_ligas)

# 7️⃣ Función para predecir resultado usando Poisson
def predecir_poisson(local, visitante, promedios):
    lambda_local = promedios[local]["gf"]
    lambda_visitante = promedios[visitante]["gf"]
    max_goles = 5
    prob_local = [poisson.pmf(i, lambda_local) for i in range(max_goles+1)]
    prob_visitante = [poisson.pmf(i, lambda_visitante) for i in range(max_goles+1)]

    # Probabilidades 1X2
    prob_1 = sum([prob_local[i]*sum(prob_visitante[j] for j in range(i)) for i in range(max_goles+1)])
    prob_X = sum([prob_local[i]*prob_visitante[i] for i in range(max_goles+1)])
    prob_2 = sum([sum(prob_local[i] for i in range(j)) * prob_visitante[j] for j in range(max_goles+1)])

    # Probabilidad Over/Under 2.5
    over_2_5 = 1 - sum([prob_local[i]*prob_visitante[j] for i in range(max_goles+1) for j in range(max_goles+1) if i+j <=2])
    under_2_5 = 1 - over_2_5

    # Ambos marcan BTTS
    btts = 1 - (prob_local[0]*sum(prob_visitante) + prob_visitante[0]*sum(prob_local))

    return {
        "1": round(prob_1*100,1),
        "X": round(prob_X*100,1),
        "2": round(prob_2*100,1),
        "Over2.5": round(over_2_5*100,1),
        "Under2.5": round(under_2_5*100,1),
        "BTTS": round(btts*100,1)
    }

# 8️⃣ Generar predicciones para todos los partidos
resultados = []
for idx, fila in df_ligas.iterrows():
    local = fila["home_team"]
    visitante = fila["away_team"]
    pred = predecir_poisson(local, visitante, promedios)
    resultados.append({
        "Liga": fila["competition_name"],
        "Fecha": fila["date_utc"],
        "Local": local,
        "Visitante": visitante,
        "1": pred["1"],
        "X": pred["X"],
        "2": pred["2"],
        "Over2.5": pred["Over2.5"],
        "Under2.5": pred["Under2.5"],
        "BTTS": pred["BTTS"]
    })

df_predicciones = pd.DataFrame(resultados)
df_predicciones.to_csv("Predicciones_5_ligas_2024_2025.csv", index=False)
print("CSV de predicciones guardado: Predicciones_5_ligas_2024_2025.csv")

# 9️⃣ Ejecutar resumen y generar CSV de cada liga automáticamente
for liga in ligas_grandes:
    resumen_liga(df_ligas, liga)

# ✅ Al final tendrás:
# - CSV Predicciones_5_ligas_2024_2025.csv
# - CSV Resumen_<Liga>_2024_2025.csv por cada liga
# Listos para subir a la app